[package]
name = "ct_rebuild_project"
version = "0.1.0"
edition = "2021"

[dependencies]
egui = "*"
eframe = "*"
image = "*"
# opencv = "*"
nalgebra = "*"
nshare = "*"
rand = "*"
fundsp = "*"
realfft = "*"
rustfft = "*"
egui_extras = "*"
